Repository algorithm-ssau/exotic-pets-catalogue, pull requests merged in 2023-05, with the labels that each got.

#28 B4 id hot fix
  server/server.js
Labels: bug, backend

#30 F9 create review form
  client/my-app/src/pages/homepage/el/Feedback/index.css
  client/my-app/src/pages/homepage/el/Feedback/index.tsx
  client/my-app/src/pages/homepage/styles/page_home.css
  client/my-app/src/pages/homepage/view/page_home.tsx
Labels: frontend

#35 F11 review component
  client/my-app/src/pages/homepage/el/ReviewCard/index.css
  client/my-app/src/pages/homepage/el/ReviewCard/index.tsx
  client/my-app/src/pages/homepage/styles/page_home.css
  client/my-app/src/pages/homepage/view/page_home.tsx
Labels: frontend

#36 F12 post review
  client/my-app/src/pages/homepage/el/Button/index.tsx
  client/my-app/src/pages/homepage/el/Feedback/index.tsx
Labels: frontend

#41 F13 interfaces have their own folder
  client/my-app/src/common/interfaces/IAdvantage.ts
  client/my-app/src/common/interfaces/IButton.ts
  client/my-app/src/common/interfaces/IReview.ts
  client/my-app/src/common/interfaces/ISpecies.ts
  client/my-app/src/pages/homepage/el/Advantage/index.tsx
  client/my-app/src/pages/homepage/el/Button/index.tsx
  client/my-app/src/pages/homepage/el/ReviewCard/index.tsx
  client/my-app/src/pages/homepage/el/SpeciesCard/data.ts
  client/my-app/src/pages/homepage/el/SpeciesCard/index.tsx
Labels: frontend

#42 F14 product card
  client/my-app/src/common/interfaces/IProduct.ts
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.css
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.tsx
Labels: frontend

#45 B6 reorganize back
  server/src/Infrastructure/Entity/AnimalsE.ts
  server/src/Infrastructure/Repository/AnimalsSQL.ts
  server/src/pages/Animals/AnimalsCtrl.ts
  server/src/pages/Animals/AnimalsR.ts
  server/src/pages/Animals/Model/AnimalsM.ts
Labels: backend

#47 added species filter
  server/src/Infrastructure/Repository/AnimalsSQL.ts
  server/src/pages/Animals/AnimalsCtrl.ts
  server/src/pages/Animals/AnimalsR.ts
  server/src/pages/Animals/Model/AnimalsM.ts
Labels: backend

#48 F15 catalogue filter
  client/my-app/src/pages/catalogue_page/styles/page_catalogue.css
  client/my-app/src/pages/catalogue_page/view/el/Filter/Filter.tsx
  client/my-app/src/pages/catalogue_page/view/el/Filter/index.css
  client/my-app/src/pages/catalogue_page/view/el/Filter/index.tsx
  client/my-app/src/pages/catalogue_page/view/page_catalogue.tsx
Labels: frontend

#51 B7 Python api init
  server/python-api/.gitignore
  server/python-api/api.py
Labels: backend

#60 B8 filter products
  server/src/Infrastructure/Entity/AnimalsE.ts
  server/src/Infrastructure/Repository/AnimalsSQL.ts
  server/src/Infrastructure/Repository/CommentsSQL.ts
  server/src/pages/Animals/AnimalsCtrl.ts
  server/src/pages/Animals/AnimalsR.ts
  server/src/pages/Animals/Model/AnimalsM.ts
Labels: backend

#61 F17 working filter
  client/my-app/package-lock.json
  client/my-app/package.json
  client/my-app/src/common/interfaces/IKingdom.ts
  client/my-app/src/common/interfaces/IOptions.ts
  client/my-app/src/common/interfaces/ISpecies.ts
  client/my-app/src/common/service/fetchS.ts
  client/my-app/src/common/service/getAnimalS.ts
  client/my-app/src/common/service/reviewS.ts
  client/my-app/src/pages/catalogue_page/el/Filter/Filter.tsx
  client/my-app/src/pages/catalogue_page/el/Filter/index.css
  client/my-app/src/pages/catalogue_page/el/Filter/index.tsx
  client/my-app/src/pages/catalogue_page/el/ProductSlider/index.css
  client/my-app/src/pages/catalogue_page/el/ProductSlider/index.tsx
  client/my-app/src/pages/catalogue_page/el/Products/index.css
  client/my-app/src/pages/catalogue_page/el/Products/index.tsx
  client/my-app/src/pages/catalogue_page/styles/page_catalogue.css
  client/my-app/src/pages/catalogue_page/view/el/Filter/Filter.tsx
  client/my-app/src/pages/catalogue_page/view/el/Filter/index.tsx
  client/my-app/src/pages/catalogue_page/view/ifc_catalogue.ts
  client/my-app/src/pages/catalogue_page/view/page_catalogue.tsx
  client/my-app/src/pages/homepage/el/SpeciesCard/data.ts
  client/my-app/src/pages/homepage/el/SpeciesCard/index.tsx
  client/my-app/src/pages/homepage/styles/swiper_custom.css
  client/my-app/src/pages/homepage/view/page_home.tsx
  client/my-app/src/store/productStore.ts
Labels: frontend

#62 F18 cart product card
  client/my-app/src/assets/image_30.png
  client/my-app/src/common/interfaces/ICart.ts
  client/my-app/src/pages/cart_page/el/CartProductCard/index.css
  client/my-app/src/pages/cart_page/el/CartProductCard/index.tsx
  client/my-app/src/pages/cart_page/styles/page_cart.css
  client/my-app/src/pages/cart_page/view/page_cart.tsx
Labels: frontend

#63 F19 cart payment
  client/my-app/src/common/interfaces/IButton.ts
  client/my-app/src/pages/cart_page/el/Button/index.css
  client/my-app/src/pages/cart_page/el/Button/index.tsx
  client/my-app/src/pages/cart_page/el/CardForm/index.css
  client/my-app/src/pages/cart_page/el/CardForm/index.tsx
  client/my-app/src/pages/cart_page/el/Payment/index.css
  client/my-app/src/pages/cart_page/el/Payment/index.tsx
  client/my-app/src/pages/cart_page/styles/cart_page.css
  client/my-app/src/pages/cart_page/view/page_cart.tsx
Labels: frontend

#66 B9 catalogueCard entity modified
  server/src/Infrastructure/Entity/AnimalsE.ts
  server/src/Infrastructure/Repository/AnimalsSQL.ts
  server/src/pages/Animals/AnimalsR.ts
Labels: backend

#67 F20 add to cart
  client/my-app/src/assets/checkmark-icon.svg
  client/my-app/src/common/el/header.tsx
  client/my-app/src/common/interfaces/ICart.ts
  client/my-app/src/common/interfaces/IPayment.ts
  client/my-app/src/common/interfaces/IProduct.ts
  client/my-app/src/common/styles/header.css
  client/my-app/src/pages/cart_page/el/CartProductCard/index.tsx
  client/my-app/src/pages/cart_page/el/Payment/index.css
  client/my-app/src/pages/cart_page/el/Payment/index.tsx
  client/my-app/src/pages/cart_page/styles/cart_page.css
  client/my-app/src/pages/cart_page/styles/page_cart.css
  client/my-app/src/pages/cart_page/view/page_cart.tsx
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.css
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.tsx
  client/my-app/src/pages/catalogue_page/el/Products/index.tsx
  client/my-app/src/store/productStore.ts
  client/my-app/tsconfig.json
Labels: frontend

#68 F21 modal window
  client/my-app/src/pages/catalogue_page/el/Filter/index.css
  client/my-app/src/pages/catalogue_page/el/Modal/index.css
  client/my-app/src/pages/catalogue_page/el/Modal/index.tsx
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.css
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.tsx
Labels: frontend

#71 B10 now u can search by specidied species
  server/src/Infrastructure/Repository/AnimalsSQL.ts
  server/src/pages/Animals/AnimalsR.ts
  server/src/pages/Animals/Model/AnimalsM.ts
Labels: backend

#72 F22 fixed search bug
  client/my-app/src/common/service/getAnimalS.ts
  client/my-app/src/store/productStore.ts
Labels: frontend

#74 F23 favorites page
  client/my-app/src/pages/cart_page/styles/cart_page.css
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.css
  client/my-app/src/pages/catalogue_page/el/ProductCard/index.tsx
  client/my-app/src/pages/favorites_page/styles/page_favorites.css
  client/my-app/src/pages/favorites_page/view/page_favorites.tsx
  client/my-app/src/store/productStore.ts
Labels: frontend
